defmodule ShompWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :shomp

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_shomp_key",
    signing_salt: "GiZ1aqcw",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  socket "/socket", ShompWeb.UserSocket,
    websocket: true,
    longpoll: true

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :shomp,
    gzip: not code_reloading?,
    only: ShompWeb.static_paths()

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :shomp
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  # Custom logging plug to debug routing issues
  plug :log_request

  plug ShompWeb.Plugs.RawBody

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug ShompWeb.Router

  def log_request(conn, _opts) do
    IO.puts("=== ROUTER DEBUG ===")
    IO.puts("Request method: #{conn.method}")
    IO.puts("Request path: #{conn.request_path}")
    IO.puts("Request URI: #{conn.request_uri}")
    IO.puts("Request host: #{conn.host}")
    IO.puts("Request port: #{conn.port}")
    IO.puts("Request scheme: #{conn.scheme}")
    IO.puts("Request query string: #{conn.query_string}")
    IO.puts("Request headers: #{inspect(conn.req_headers)}")
    IO.puts("==================")
    conn
  end
end
